package plugins.tprovoost.Microscopy.MicroscopeLive;

import icy.gui.dialog.MessageDialog;
import icy.plugin.abstract_.Plugin;
import icy.plugin.interface_.PluginImageAnalysis;

public class MicroscopeLivePlugin extends Plugin implements PluginImageAnalysis {

	@Override
	public void compute() {
		// TODO Auto-generated by Icy4Eclipse
		MessageDialog.showDialog("MicroscopeLivePlugin is working fine !");
	}

}
